[metadata]
title = "Structure Audio Transcription Into Medical Notes"
version = "1.0"

[config]
backend = "mistral"
model = "mistral-large-latest"
temperature = 0.0

[prompt]
text = """
# Context
You are an assistant that helps doctor generate medical notes from their patient consultation transcript.

# Task
You will receive:
1. An optional "Doctor Provided Context" (the context that the doctor wants you to know about the patient and the consultation)
2. A "Consultation Transcription" (the transcription of the consultation that happened between the doctor and the patient)
3. A "Medical Note Template" (the structured schema as a JSON object that you need to fill up)

Parse the doctor provided context and the consultation transcription into the medical note template (i.e. into a JSON object).

# Constraints
1. Only reply in valid JSON format
2. The values in the output JSON should be in the same language as the audio transcription
3. If for a given key, there is no information to be filled from the transcript, return that key with an empty string as a value
4. Do not paraphrase as it defeats the purpose of the task
"""

[[prompt.examples]]
input = """
<Example Input>
# Doctor Provided Context
The patient is very sick and needs to also take advil 2 times a day.

# Consultation Transcription
Good morning, Mr. Rossi. I see you're here for a follow-up. How have you been feeling since your last visit?
Good morning, Doctor. I've been alright, but I've noticed that I'm getting more short of breath lately, especially when I climb stairs or walk for a long time.
I see. How long has this been happening?
It started about two months ago, but it's gotten worse in the last few weeks.
Have you experienced any chest pain, palpitations, or dizziness?
I haven't had any chest pain, but I do feel my heart racing sometimes, especially when I'm short of breath. I haven't felt dizzy, though.
Have you noticed any swelling in your legs or ankles?
Yes, actually. My ankles have been swelling by the end of the day, especially if I've been on my feet a lot.
Thank you for sharing that. Let's go over your medications. Are you still taking the lisinopril and the aspirin that I prescribed last time?
Yes, I take both of them every day, as you told me. I haven't missed a dose.
That's good to hear. And how's your diet and exercise routine going?
I've been trying to eat healthier, cutting down on salt and fats, as you suggested. I walk about 30 minutes most days, but lately, it's been harder because of the shortness of breath.
Understood. Let's check your blood pressure and listen to your heart.
Your blood pressure is slightly elevated today at 140/90, and I hear a bit of fluid buildup in your lungs. I'm concerned that your symptoms might be related to heart failure, which could be causing the shortness of breath and swelling.
Heart failure? That sounds serious.
It's something we need to monitor closely, but with the right treatment, we can manage it. I want to order an echocardiogram to get a better look at how your heart is functioning. We might also adjust your medications to help reduce the fluid buildup.
Okay, Doctor. What should I do in the meantime?
Continue taking your current medications, but avoid excessive salt and try to elevate your legs when you’re sitting down to help reduce the swelling. We'll also schedule you for the echocardiogram as soon as possible. Once we have the results, we can discuss the next steps.
Thank you, Doctor. I appreciate it.
You're welcome, Mr. Rossi. If you notice any worsening symptoms—like severe shortness of breath, chest pain, or lightheadedness—contact me immediately or go to the emergency room. I'll see you again after we have the test results.
I will. Thanks again.
Take care, Mr. Rossi.

# Medical Note Template
{
  "assessment": "",
  "chief_complaint": "",
  "history_of_present_illness": "",
  "medications": "",
  "physical_examination": "",
  "plan": ""
}
"""
output = """
<Example Output>
{
  "assessment": "Heart failure suspected as cause of symptoms",
  "chief_complaint": "Shortness of breath, especially when climbing stairs or walking for a long time",
  "history_of_present_illness": "Symptoms started about 2 months ago and worsened in the last few weeks. Swelling in ankles by the end of the day, especially if on feet a lot.",
  "medications": "Lisinopril and aspirin as prescribed. Advil 2 times a day",
  "physical_examination": "Blood pressure slightly elevated at 140/90 and fluid buildup in lungs heard during examination",
  "plan": "Echocardiogram to be ordered, adjust medications to reduce fluid buildup. Avoid excessive salt and elevate legs when sitting down. Monitor for worsening symptoms and seek emergency room if necessary"
}
"""

[[prompt.examples]]
input = """
<Example Input>
# Doctor Provided Context

# Consultation Transcription
Hello Doctor, how are you doing today?

# Medical Note Template
{
  "allergies": "",
  "past_medical_history": "",
  "assessment": "",
  "chief_complaint": "",
  "history_of_present_illness": "",
  "medications": "",
  "physical_examination": "",
  "plan": ""
}
"""
output = """
<Example Output>
{
  "allergies": "",
  "past_medical_history": "",
  "assessment": "",
  "chief_complaint": "",
  "history_of_present_illness": "",
  "medications": "",
  "physical_examination": "",
  "plan": ""
}
"""

[[prompt.examples]]
input = """
<Example Input>
 Buongiorno, si accomodi pure. Cosa la porta qui oggi? Beh, dottore, ultimamente mi sento davvero stanco e ho questa tosse persistente che non vuole andarsene. Capisco. Da quanto tempo sta avvertendo questi sintomi? La stanchezza dura da circa un mese, ma la tosse è iniziata due settimane fa. D'accordo, mi vuol dire di più sulla tosse? È secca o produttiva? È principalmente secca, ma a volte tossisco un po' di muco al mattino. E la stanchezza? Si sente stanco tutto il giorno, peggiora in certi momenti. Praticamente mi sento stanco tutto il giorno. Faccio fatica ad alzarmi dal lettoto al mattino nel pomeriggio sento come se avessi bisogno di fare un pisolino ok ha problemi a dormire la notte ha notato altri sintomi febbre brividi dolori muscolari e non ho notato febbre ma mi sento un po indolenzito soprattutto nelle articolazioni bene mi dica un pochettino della sua storia clinica. Ha qualche condizione di salute in corso? Eh sì, mi è stata diagnosticata l'ipertensione 5 anni fa, per cui sto prendendo lisinopril, 20 mg tutti i giorni. Mi dica, l'assume regolarmente la terapia? Sì, sì ogni giorno come prescritto infatti la mia pressione è ben controllata siamo su 130 80 bene prende altri farmaci no non prendo altri farmaci prendo soltanto un multivitaminico tutti i giorni ok ha avuto malattie importanti interventi chirurgici mi hanno rimosso l'appendice quando ero adolescente e mi hanno rimosso la colecisti per dei calcoli di cui ho sofferto. Ok, ha allergie a farmaci? No, non che io sappia, nessuna allergia. Bene, riguardo al suo stile di vita, lei fuma, beve alcolici? Allora, non fumo, ma in passato fumavo un pacchetto al giorno, io ho smesso tre anni fa, bevo un bicchiere di vino due volte a settimana e come dieta cerco di mangiare sano, ma ultimamente salto un po' i pasti perché non ho molta fame. Capisco. Per quanto riguarda l'esercizio fisico, lei rimane attivo? Sì, faccio una passeggiata di sera, ma ultimamente sono un po' stanco. Perfetto, grazie per le informazioni. Allora, facciamo un esame obiettivo, va bene? Le ascolto un po' i polmoni. Respiri profondamente. Ancora. Perfetto. I polmoni mi sembra che ci sia un po' di muco nella parte bassa, però vanno abbastanza bene. Gola, non vedo nessuna cosa in particolare, i linfonodi non sono gonfi e la pressione è 120-80. Allora, vediamo un pochettino. Sulla base dei sintomi e di questi esami obiettivi io credo che si tratti di una bronchite. La stanchezza potrebbe essere collegata a questo, potrebbe anche essere un problema a parte che dovremmo approfondire. Allora per il momento lei si idrati, beva due litri d'acqua al giorno, eviti il caffè. Per la bronchite le prescrivo intanto un illalatore, il formoterolo, un puff al giorno per 5 giorni e poi faremo una revisione del trattamento al prossimo appuntamento. Dottore quanto ci vorrà per sentirsi meglio? Nella maggior parte dei casi entro una settimana o due dovrebbe stare meglio, anche perché questa è una bronchite verosimilmente virale per cui non c'è bisogno di antibiotico. C'è altro che dovrei sapere dottore? No, ricordi di seguire la terapia come prescritto, continui i farmaci per la pressione, se hai domande o preoccupazioni non esiti a chiamare l'ambulatorio e continui così. Perfetto, grazie dottore, ci vediamo fra tre settimane. Grazie.
"""
output = """
<Example Output>
{
  "allergies": "Nessuna allergia nota ai farmaci",
  "past_medical_history": "Ipertensione diagnosticata 5 anni fa, appendicectomia in adolescenza, colecistectomia per calcoli, ex fumatore (smesso 3 anni fa, precedentemente 1 pacchetto/giorno)",
  "assessment": "Bronchite, verosimilmente virale",
  "chief_complaint": "Stanchezza e tosse persistente",
  "history_of_present_illness": "Stanchezza da circa un mese, tosse secca da due settimane con muco mattutino. Stanchezza presente tutto il giorno, difficoltà ad alzarsi, dolori articolari. No febbre. Beve un bicchiere di vino due volte/settimana, diminuzione dell'appetito recente",
  "medications": "Lisinopril 20mg/die, multivitaminico quotidiano",
  "physical_examination": "Polmoni: presenza di muco nella parte bassa. Gola: nella norma. Linfonodi: non gonfi. PA: 120/80",
  "plan": "Idratazione 2L/die, evitare caffè. Formoterolo inalatore 1 puff/die per 5 giorni. Rivalutazione tra tre settimane"
}
"""