services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh ./scripts/dev_server.sh
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - ambiantcare_home:/home/ambiantcare
      - ambiantcare_data:/data
    user: "1000:1000"
    environment:
      - HOME=/home/ambiantcare
      - DATABASE_HOSTNAME=postgres
    depends_on:
      - postgres
    tty: true
    stdin_open: true

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ambiantcare_postgres:/var/lib/postgresql/data

volumes:
  ambiantcare_postgres:
  ambiantcare_home:
  ambiantcare_data:
